name: Clean Commits
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main brain
        uses: actions/checkout@v2
        
      - name: Check out to a temporary branch
        run: |
          git checkout --orphan TEMP_BRANCH

      - name: Add all the files
        run: |
          git add -A

      - name: Commit Changes
        run: |
          git commit -am "Initial commit"


      - name: Delete Old Branch
        run: |
          git branch -D master


      - name: Rename the temporary branch to master
        run: |
          git branch -m master

      - name: Finally, force update to our repository
        run: |
          git push -f origin master


